OH HAI: I CAN HAS WISHEZ PLZ
  SO DAT I CAN HAS HUGS TIEM AN PLAY TIEM AN SLEEP TIEM AN NOM TIEM
  AS NICE GREEDEE KITTEH
  I CAN PLZ MANEGE TEH WISHEZ

  MISHUN: MAK NEW WISH
    I CAN HAZ LOGGD IN
    WEN I MAK "CHEEZBURGER" WISH
    DEN I C "CHEEZBURGER" ON ME WISHEZ LIT
